before_commands:
  - composer install
filter:
    excluded_paths:
        - 'vendor/*'
tools:
  php_code_coverage:
    enabled: true
    filter:
      paths: [ / ]
    test_command: ./vendor/bin/phpunit
  php_code_sniffer:
    enabled: true
    filter:
      paths: [ / ]
    config:
      standard: PSR2
  php_cpd:
    enabled: true
  php_cs_fixer:
    enabled: true
    config:
      level: psr2
    filter:
      paths: [ / ]
  php_mess_detector:
    enabled: true
    filter:
      paths: [ / ]
  php_analyzer: true
  sensiolabs_security_checker: true
  php_pdepend: true
  php_loc: true